### PR TITLE
:shipit: v1.13.0

### PR DESCRIPTION
**Pull request by chancestrickland**
Update Develop with v1.13.0 release

### CODE REVIEW

**Comment by jsomsanith** [comment]
Hi people.
This version was set on nov 18, is there a plan to publish it ? A roadmap ?

**Comment by JWess** [comment]
I am also in need of this version being released. Any ETA?

**Comment by DanPurdy** [comment]
This wont be released. When i ran out of time to work on sass-lint we'd made some progress in a v2 and this branch has that work on it. IF it gets released it will be a v2 at minimum. I know i've said it a lot but i'm really hoping to find some time to get back into working on this project.

**Pull request merged**
