### PR TITLE
Fix function name formats

### LINKED ISSUE #434: function-name-format doesn't take exception to built-in CSS functions
See the discussion on #344. The rule also needs to have exceptions for the other functions that are part of vanilla CSS.

E.g.
```scss
.class {
    background: linear-gradient(to bottom, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0) 100%);
}
```

Will throw lint warnings for `linear-gradient`.

### PR DESCRIPTION
**Pull request by DanPurdy**
As discussed #434 The function name format rule wasn't taking into account a lot of default CSS function names.

After trawling the web for as definitive list as possible I've added my findings to the whitelist. Some of the functions are either very very early in the w3c draft process or have even lost support in most of the browsers around today but I feel it's important to keep them there out of completeness sake

closes #434 

Again not sure it's worth a hotfix when 1.4.0 is around the corner

`DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com`

### CODE REVIEW

**Comment by DanPurdy** [comment]
Need to add all the sass functions too

**Comment by DanPurdy** [comment]
TODO:

- [x] RGB Functions
- [x] HSL Functions
- [x] Opacity Functions
- [x] Other Color Functions
- [x] String Functions
- [x] Number Functions
- [x] List Functions
- [x] Map Functions
- [ ] Selector Functions
- [ ] Introspection Functions
- [x] Miscellaneous Functions

**Comment by DanPurdy** [comment]
Ready for review

**Comment by benthemonkey** [comment]
LGTM. Merging.

**Pull request merged**
