### PR TITLE
Fix false positive for valid css with space-around-operator

### LINKED ISSUE #394: Space around operator false positive
The space-around-operator rule recently added to dev branch has an issue with valid css using negative values.

```css
.foo { margin: -15px -15px; }
``` 

Sass 1.3.2, node 5.0.0

### PR DESCRIPTION
**Pull request by bgriffith**
This PR fixes a bug where valid css would: 
1 - Be flagged up as requiring a space
2 - Cause a error with the parser.

The css in question is negative values for margin, top etc

`margin: -15px;`
 
Ps. Thanks to @DanPurdy for catching it!

Closes #394 
DCO 1.1 Signed-off-by: Ben Griffith gt11687@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
How about variable/selector names, I know they're not targeted but in anticipation of gonzales changes that may affect this it would be good to have them in?

**Comment by bgriffith** [comment]
I don't feel that's necessary. Since we're only ever targeting `['condition', 'atruleb', 'value', 'atrulerq']` to begin with, selectors should never come up. I know you could potentially future proof it (somehow?!) but I can't see any reason why a character within a selector would ever be classed as an operator.

**Comment by DanPurdy** [comment]
'should' :wink: 

Update this and it's good to go

**Comment by DanPurdy** [comment]
grr update again and let me know.

**Comment by bgriffith** [comment]
I've clicked update. Now it's just waiting game...

**Pull request merged**
