### PR TITLE
Fix no-color-literals raising warning on variables named as a color

### PR DESCRIPTION
**Pull request by brettlangdon**
Addresses a fix for the issue outlined in #538.

DCO 1.1 Signed-off-by: Brett Langdon <me@brett.is>

### CODE REVIEW

**Comment by DanPurdy** [comment]
So we discussed this a long time ago and sort of decided against this sort of exception but I'm willing to reopen the discussion

**Comment by brettlangdon** [comment]
Rebased branch with `develop` since GitHub told me I should :)

**Comment by DanPurdy** [comment]
Thanks for your contribution @brettlangdon We carried on from the changes you made to give everyone the option to include linting of color literals in variable names or map identifiers, hopefully that solves the original issue for you too.

**Comment by brettlangdon** [comment]
@DanPurdy thanks! I think that will fit my needs just fine.

**Pull request closed without merging**
