### PR TITLE
Add unit test for ignored files

### PR DESCRIPTION
**Pull request by mven**
It seems there must be no space between each ignored pattern for glob to recognize them all. I fixed that, as well as added a unit test to test against ignored files. I ran `npm test` and it passed successfully.

```bash
cli
    ✓ should return help instructions (120ms)
    ✓ should return a version (119ms)
    ✓ should not include ignored paths (461ms)
```
...
```bash
 zero unit
    ✓ [include: false]
    ✓ [include: true]

  60 passing (219ms)
```

### CODE REVIEW

**Comment by mven** [comment]
So close! lol.

**Comment by mven** [comment]
Looks like the the error is that sass-lint couldn't be installed globally on node 4.0 
https://travis-ci.org/sasstools/sass-lint/jobs/79392140#L136

**Comment by DanPurdy** [comment]
@Snugug @mven whats the status here? Have we decided on a way forward?

**Comment by DanPurdy** [comment]
Incoming PR to sort this

**Pull request closed without merging**
