### PR TITLE
Adding path absolute polyfill

### PR DESCRIPTION
**Pull request by ianand2**
Hi
    This PR is for: https://github.com/sasstools/sass-lint/issues/672
I'm not sure if there is any testing you would like to see here. Travis already seems to be testing it on node 0.10, though when testing, the fs-extra package is patching the path module with the isAbsolute function, https://github.com/jprichardson/node-fs-extra/blob/9ed01a7bc016731798ebb2eee9b5933860d46811/lib/ensure/symlink-paths.js#L3, so this was not caught in tests.

DCO 1.1 Signed-off-by: Anand <ianand2@gmail.com>

### CODE REVIEW

**Comment by dcai-medallia** [comment]
+1

**Comment by DanPurdy** [comment]
@dcai-medallia Please don't put +1 comments in PR's or issues, you can use the Github reactions to add your support but +1's just clutter the task.

**Comment by DanPurdy** [comment]
@ianand2 I'll close this PR and use #706 instead I just added some appveyor and travis changes for node 0.10.x on top of your changes thanks again 👍

**Comment by ianand2** [comment]
@DanPurdy regarding the fs-extra comment, it was polyfilling path.isAbsolute when running the tests. I think the sequence of loading the libraries is such that the polyfill happens before sass-lint starts when testing, so this error was not caught as part of the test suite. This is still necessary to be able to run it in node 0.10

**Comment by DanPurdy** [comment]
@ianand2 So we haven't been testing against 0.10 for a few weeks now due to the random issues we were having that seemed related to our use of child processes in our tests and the spurious error codes they would sometimes throw out when we were testing for a specific error code, your change actually seems to have resolved a lot of those so it seems like we were just looking in the wrong place!

I've re implemented the 0.10 tests for Travis and Appveyor. On appveyor it's set as an acceptable failure as there are two issues that we know aren't issues but we'll make sure all of our other tests pass.

Out of interest is there any reason why you haven't / can't upgrade your node version?

**Comment by ianand2** [comment]
Fixing bugs by accident, thats always nice :) 
We are in the process of migrating, we just haven't had any blocker issues with 0.10 so far for it to be a high priority.

**Comment by DanPurdy** [comment]
Makes sense, thanks! 👍

**Pull request closed without merging**
