### PR TITLE
Hotfix master - Fix issue where mixin-name-format incorrectly lints extends

### LINKED ISSUE #396: Cannot read property 'content' of undefined when @extend from external file
`Sass-lint` crashes when encounter `@extend` from external file.
For example I use PureCSS, and 
```
.test
  @extend .pure-u-1-6
```

In this case I get Cannot read property 'content'  error

### PR DESCRIPTION
**Pull request by bgriffith**
Fixes an issue where the mixin-name-format rule would incorrectly lint `@extends` aka class names when used with Sass syntax.

Closes #396

DCO 1.1 Signed-off-by: Ben Griffith gt11687@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Why is coveralls not reporting back..

**Comment by DanPurdy** [comment]
so does this have issues with the other `@-rules` such as `@debug` and `@at-root`

**Comment by bgriffith** [comment]
No because they aren't classed as includes.

**Comment by bgriffith** [comment]
No idea about coveralls.

**Comment by bgriffith** [comment]
Gah can't edit a comment in this app. I'll add some extra tests just to make sure. Assuming again!

**Comment by benthemonkey** [comment]
If this is branched off master, then coveralls isn't included in the .travis.yml file on master yet. Want me to make a hotfix to master to add coveralls?

This PR looks good to me.

**Comment by benthemonkey** [comment]
Maybe the comment I made on line 1 isn't accurate after this PR. Should that be deleted?

**Comment by DanPurdy** [comment]
I'm assuming #398 isn't reporting with coveralls because it's out of date then?

Unfortunately if you submit a hotfix to master we wouldn't be able to merge it because of coveralls! :smile:

**Comment by benthemonkey** [comment]
Making PR.

**Comment by benthemonkey** [comment]
Again, Coveralls is upset that lines of code were added that aren't getting hit by our current unit tests. These two lines are never hit:

https://coveralls.io/files/1462450682#L22
https://coveralls.io/files/1462450682#L31

**Comment by DanPurdy** [comment]
Once this is updated and passed we'll release 1.3.3 and then focus on getting 1.4.0 out of the door.

**Comment by bgriffith** [comment]
Updated.

**Comment by benthemonkey** [comment]
LGTM, shall I merge?

**Comment by DanPurdy** [comment]
Hold off for a moment, I'll do all of this as part of the 1.3.3 release.

**Pull request merged**
