### PR TITLE
Add coveralls for code coverage

### PR DESCRIPTION
**Pull request by benthemonkey**
Hooray for promoting test coverage!

I submitted this because I was interested in learning about setting up code coverage tools. Also I wanted to know whether the test cases for my rules are covering every branch of the code.

Feel free to close this PR if there are reasons to not include a code coverage tool. If folks are interested in merging this, then @Snugug (or someone with admin access) will have to set up coveralls.io to track this repo.

Additionally, if this gets merged we should add the coveralls badge to the readme.

DCO 1.1 Signed-off-by: Ben Rothman <bensrothman@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
@benthemonkey thanks for this but could we open up issues before starting these types of PR please. Gives everyone a chance to discuss it or give any info on other plans we may have had. I'll leave this one for @Snugug

**Comment by benthemonkey** [comment]
OK will do next time.

**Comment by benthemonkey** [comment]
I just looked over the language I used in this PR. I updated it to not be as assuming, given that I didn't ask permission before submitting this PR. :smile:

**Comment by benthemonkey** [comment]
@DanPurdy @Snugug This has been sitting for awhile. I don't mind closing it, but I'd like to hear back about it, when you get the chance.

**Comment by Snugug** [comment]
We're busy!

I'm OK merging this in as long as you update to the latest `develop` (currently can't be merged).

We can debate the merits of code coverage elsewhere

**Comment by benthemonkey** [comment]
Done. I'm not trying to be pushy. I know you were away doing exciting things. :smile:

**Comment by Snugug** [comment]
:P

**Pull request merged**
