### PR TITLE
Add rule: no-vendor-prefix

### LINKED ISSUE #34: New Rule: Vendor Prefix
As per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#vendorprefix)

### PR DESCRIPTION
**Pull request by DanPurdy**
Add rule `no-vendor-prefix` to prevent the use of vendor prefixes.

By default it will warn/error for the following prefixes:
* `webkit`
* `moz`
* `ms`

The rule includes two options
* `additional-identifiers`: an array of extra prefixes you'd like to lint for
* `excluded-identifiers`: an array of prefixes you would like to remove from the current linting options.

Closes #34 

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by Snugug** [comment]
no-vendor-prefixes please

**Comment by DanPurdy** [comment]
Will do

**Comment by Snugug** [comment]
Thanks!

**Comment by Snugug** [comment]
:cry: why are there conflicts? I thought we had figured this out by moving tests to their own files?

**Comment by bgriffith** [comment]
Boo! Probably git giving up on `lib/config/sass-lint.yml`

**Comment by DanPurdy** [comment]
Yeah it was, it's all good!

**Comment by Snugug** [comment]
:+1:

**Pull request merged**
