### PR TITLE
Fix previous.is is not a function

### LINKED ISSUE #887: Warning: previous.is is not a function
```
Running "sasslint:target" (sasslint) task
Warning: previous.is is not a function Use --force to continue.

Aborted due to warnings.


Execution Time (2016-10-04 17:03:40 UTC+2)
loading tasks     1.3s  ███████████████████████████████████████ 86%
sasslint:target  220ms  ███████ 14%
Total 1.5s


```

### PR DESCRIPTION
**Pull request by ajsb85**
**What do the changes you have made achieve?**

**Are there any new warning messages?**

**Have you written tests?**

**Have you included relevant documentation**

**Which issues does this resolve?**
Fixes  #887, #874

`<DCO 1.1 Signed-off-by: Alexander J. Salas B a.salas@ieee.org>`

### CODE REVIEW

**Comment by ajsb85** [comment]
This solution works.
Can you merge this @DanPurdy?

**Comment by DanPurdy** [comment]
Tests are failing, can't merge this until they pass i'm afraid. Can you please provide all the required information in the issues and the PR you've opened too, It's not clear at all what is going wrong and in what situations.

**Comment by ajsb85** [comment]
@DanPurdy It's an error of the CLI tool.

```
Running "sasslint:target" (sasslint) task
Warning: previous.is is not a function Use --force to continue.

Aborted due to warnings.
```

Something the `previous` function is undefined.

**Comment by DanPurdy** [comment]
@ajsb85 Yeah I see what the error is but there's no explanation in the issues about what you were trying to do at the time and what was making it fail and what steps we can take to recreate it. The reason I ask is that your PR is failing our tests so has broken something else, it's hard for anyone else to look into this if they don't know how to recreate the error in the first place. 

If you could add a little more detail to the issue itself that would be very helpful.

**Comment by ajsb85** [comment]
@DanPurdy I dont have more information about the issue.
I fix the issue, and It's working.
To reproduce by yourself I can send you by email a list of files to test.
Thanks.

**Comment by DanPurdy** [comment]
closing in favour of #1125

**Comment by DanPurdy** [comment]
Released in 1.12.0

**Pull request closed without merging**
