### PR TITLE
Add hex notation rule

### LINKED ISSUE #77: New Rule: Hex Notation
Check hexadecimal values are either all lowercase (default) or all uppercase.

as per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexnotation)

### PR DESCRIPTION
**Pull request by DanPurdy**
Add a rule to enforce the consistency of hexadecimal value cases.

Add 3 new helper functions
* isNumber - check is integer
* isUpperCase - check if string passed is all uppercase
* isLowerCase - check if string passed is all lower case

I kept the case helper functions separate to allow use in other rules to follow (property name case checking?). They allow you to pass many non alphanumeric characters too as part of a string without erroneously flagging them as upper or lower case.

Would like to add tests for all the helper functions too in the future.

Closes #77

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by Snugug** [comment]
Please resolve the merge conflicts

**Comment by DanPurdy** [comment]
Done though, I'm guessing we may see these again once the next PR gets merged to master :stuck_out_tongue:

**Comment by DanPurdy** [comment]
Nice catch, will sort that out.

**Comment by bgriffith** [comment]
Looking good!

**Pull request merged**
