### PR TITLE
Add Brace Style rule

### LINKED ISSUE #36: New Rule: Brace Style
As per [ESLint](http://eslint.org/docs/rules/brace-style)

### PR DESCRIPTION
**Pull request by bgriffith**
Adds a rule that will enforce the use of the chosen brace style. Can be `1tbs`, `stroustrup` or `allman`.

## Warning messages

When `style: allman` and brace on same line:
> Brace must be on a new line

When `style: 1tbs` or `style: stroustrup` and brace on new line:
> Brace must be on same line as condition

**For `@else` and `@elseif` statements**
When `style: allman` or `style: stroustrup` and statement on same line as previous brace:
> Statement should begin on a new line

When `style: 1tbs` and statement on new line:
> Statement on next line should begin on the current line

## Todo

- Add option and support to allow for single-line statements

Closes #36 

DCO 1.1 Signed-off-by: Ben Griffith <gt11687@gmail.com>

### CODE REVIEW

**Comment by Snugug** [comment]
YAS thank you for this!

A couple of comments; otherwise GTG.

**Comment by bgriffith** [comment]
Ok new single-line-statements functionality as well as more tests have been pushed.

**Comment by bgriffith** [comment]
Ah not there yet, found an issue.

**Comment by bgriffith** [comment]
Ok we're good!

**Comment by Snugug** [comment]
:+1:

**Comment by DanPurdy** [comment]
That is great, some comprehensive test situations there too.

**Pull request merged**
