### PR TITLE
Add rule: variable-name-format

### PR DESCRIPTION
**Pull request by benthemonkey**
Add rule: variable-name-format which validates that all variables adhere to a convention

Options:
`allow-leading-underscore`: Allow variables to begin with an underscore (default true)
`convention`: one of `hyphenatedlowercase` (default), `camelcase`, `snakecase`, or a RegExp
`convention-explanation`: defaults to `should match regular expression /[regex]/[flags]`, explanation if the RegExp from `convention` fails

I took the patterns for `isCamelCase`, `isHyphenatedLowercase` and `isSnakeCase` from how scss-lint implements them for consistency between projects.

I'll add the related rules to this Pull Request, but since they are very similar I wanted to get feedback early to avoid applying fixes across four rules.

Part 1 of 4 for #17 

DCO 1.1 Signed-off-by: Ben Rothman <bensrothman@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
Looks good, only thing I feel missing is a hyphenated string in the `hyphenated lowercase` helper tests. Also the documentation file but otherwise I'm happy with it! 

Thanks @benthemonkey

**Comment by DanPurdy** [comment]
Also let's keep the pull requests separate for each rule. Makes it a bit easier for us to keep track of the changes when we do a release. That ok?

**Comment by bgriffith** [comment]
Hey @benthemonkey, thanks for the PR. Could you make sure to link to the issues so it's easier to see what this is related to? Thanks!

**Comment by DanPurdy** [comment]
Awesome, this looks great.

So i know the change to `Sass` syntax wont affect this much but would you mind adding test for `.sass` too.

#256 and #258 both have examples of us providing these, we just want to cover all bases moving forward! If you wouldn't mind just adding these and then I'll happily merge this in! 

Thanks again

**Comment by DanPurdy** [comment]
Also, in the documentation maybe a quick demonstration and example of each of the other possible options as they are specified options. Just to be thorough. @Snugug @bgriffith what do you guys reckon?

**Comment by benthemonkey** [comment]
Why do we only count the number of warnings in test cases? Isn't that prone to missing issues?

Wouldn't the library be more robust if each unit test looked at the smallest amount of sass/scss to produce a warning, and have the sass/scss directly in the test instead of in a file?

Like this (could be significantly cleaned up with some helper functions):

```javascript
describe('variable name format', function () {
  describe('[convention: hyphenatedlowercase]', function () {
    lint.test(
      {
        'text': '$hyphenated-lower-case: 1;',
        'format': 'scss',
        'filename': 'none'
      },
      {
        'variable-name-format': [
          1,
          {
            'convention': 'camelcase'
          }
        ]
      },
      function (data) {
        it('correct warning count', function () {
          lint.assert.equal(1, data.warningCount);
        });

        it('contains variable name in message', function () {
          lint.assert.ok(data.messages[0].message.indexOf('hyphenated-lower-case'));
        });

        it('contains correct convention in message', function () {
          lint.assert.ok(data.messages[0].message.indexOf('camelCase'));
        });
      }
    );
  });
});
```

**Comment by DanPurdy** [comment]
This is definitely something that should be looked at and added and something that @bgriffith and I for certain have spoken about and I'm sure @Snugug is the same. I feel it works alongside what we have not instead of too.

My simple answer would be, it was like this when I got here. :smile:  My slightly more long winded answer is that we've found time and time again with some of the rules in the early days that the context of what was being tested i.e. nested rules etc affected certain other contexts or caused outright failures, so in essence we are making sure that the amount of errors we have designed to be reported are. There was a bug in `mixins-before-declarations` for example that only reared it's head when it followed another rule block, which without being EXTREMELY thorough would probably have been missed by small single line/block Sass/scss tests. The other issue is some of the parsing errors that our AST occasionally throws up again being sometimes fairly context specific.

I definitely think your suggestion of actually counting the instances of an error message drastically increases the reliability of the tests and would be a welcome addition and I also feel like i'd love to see some full scale tests too with a 'real-world' file being linted with all the rules active and everything being checked for interoperability and any clashes or conflicts.

Let's create an issue from this though and look to improve them as we move forward, the more tests the better.

**Comment by DanPurdy** [comment]
:+1:

**Pull request merged**
