### PR TITLE
Hotfix develop - Silence output on no errors

### LINKED ISSUE #141: outputResults should only do so if warnings or error present
[outputResults](https://github.com/sasstools/sass-lint/blob/develop/index.js#L96-L106) should only output results if there are warnings or errors present.

### PR DESCRIPTION
**Pull request by DanPurdy**
Please merge #170 first, also see #170 for the description of why the tests are failing here.

Silences error output when no warnings or errors are present in linted files. Also improves the handling of writing output to the file system with completion/error messages but no error thrown.

closes #141

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Will close for the time being.

**Comment by DanPurdy** [comment]
Don't know why i ended up opening this again.. Should remain closed until the master hotfix is merged

**Comment by bgriffith** [comment]
Update this and I'll merge.

**Comment by DanPurdy** [comment]
I know what the errors will be here, it's a consequence of merging in the silence output on no errors work in #171 and #170 will update later on.

**Comment by Snugug** [comment]
This all looks good to me, just need the merge conflict resolved

**Comment by DanPurdy** [comment]
@Snugug @bgriffith it's good to go.

**Pull request merged**
