### PR TITLE
Add No Debug and No Warn rules

### LINKED ISSUE #37: New Rules: No Debug/Warn
Two rules, one for debug, one for warn

### PR DESCRIPTION
**Pull request by bgriffith**
This pull request adds 2 rules. One to detect and flag up the use of @debug and another to detect and flag up the use of @warn

Closes #37 

DCO 1.1 Signed-off-by: Ben Griffith <gt11687@gmail.com>

### CODE REVIEW

**Comment by Snugug** [comment]
I'm going to ask you to write docs for this as soon as I add one doc as an example to follow. Per https://github.com/sasstools/sass-lint/issues/39

**Comment by bgriffith** [comment]
Sure no probs.

**Comment by Snugug** [comment]
Take a look at the [docs](https://github.com/sasstools/sass-lint/tree/master/docs/rules) to see the pattern to follow.

Also, it looks like there are merge conflicts from the work I did on the plane. I bet it's with the `sass-lint.yml` file.

**Comment by Snugug** [comment]
You're awesome. Thanks!

**Comment by bgriffith** [comment]
Yeah it was just the config file, quick fix!

**Pull request merged**
