### PR TITLE
Add disable-next-line

### LINKED ISSUE #995: sass-lint:disable-next-line
At the moment, you can do:

```sass
overflow-x: scroll !important; // sass-lint:disable-line no-important
```

Or:

```sass
// sass-lint:disable no-important
overflow-x: scroll !important;
// sass-lint:enable no-important
```

The first is not ideal when you want to add a reason/description and the line is already quite long, and the second is unnecessarily verbose.

TSLint supports a `tslint:disable-next-line` alternative, which would look like this:

```sass
// sass-lint:disable-next-line no-important -- The reason for this is because ...
overflow-x: scroll !important;
```

It would be nice to have this option.

### PR DESCRIPTION
**Pull request by aszwemin**
**What do the changes you have made achieve?**

Closes #995 

**Are there any new warning messages?**

No

**Have you written tests?**

Yes

**Have you included relevant documentation**

Yes

**Which issues does this resolve?**

#995 

`<DCO 1.1 Signed-off-by: Anna Szwemin anna.szwemin@gmail.com>`

### CODE REVIEW

**Comment by aszwemin** [comment]
Is there some issue with this pr preventing it from being merged?

**Comment by Ilya1vanov** [comment]
Guys, merge it, please. I feel a lack of this feature :)

**Comment by diogocorrea** [comment]
Hi, @aszwemin,
Looks like this PR is ok and the only think left to do is rebase the commits. Could you do it for us?

**Comment by aszwemin** [comment]
Hi @diogocorrea, I've rebased the pr. The AppVeyor check seems to be sad but it looks like reasons unrelated to the pr itself and Travis is not updating the status on the pr (if you follow the link, it passed). Let me know if you need me to do anything else.

**Comment by diogocorrea** [comment]
Hi, @Snugug,
It seems that there is something going on with the integration tests. Could you take a look at it for us?

**Comment by diogocorrea** [comment]
@DanPurdy @bgriffith @benthemonkey Could any fo you guys help us to get this PR merged? 
This feature would be extremely helpful for those who use sass-lint and prettier together. 
Thank you!

**Comment by diogocorrea** [comment]
Hi @Snugug, @DanPurdy, @bgriffith, @benthemonkey. 
Sorry for the insistence, but if any of you could help getting this PR merged I would be very glad. 
Thank you, guys.

**Comment by diogocorrea** [comment]
Hi @srowhani,
It seems that there is something going on with the integration tests. Could you take a look at it for us?
This feature would be extremely helpful for those who use sass-lint and prettier together.
Thank you!

**Comment by srowhani** [comment]
Hi. I'd like to first take the time to thank you for your contribution.

I'm updating some components of the repo to have CI pass, and have it so that future releases can be more frequent.

I'll soon look into merging this PR.

**Pull request merged**
