### PR TITLE
Added --fix CLI command to automatically fix errors by rebuilding AST

### PR DESCRIPTION
**Pull request by srowhani**
See #728
**What do the changes you have made achieve?**
Added fix.
**Are there any new warning messages?**
Nope.
**Have you written tests?**
Nope.
**Have you included relevant documentation**
Yes.
**Which issues does this resolve?**
One previously mentioned.
`<DCO 1.1 Signed-off-by: Seena Rowhani seenarowhani95@gmail.com>`

### CODE REVIEW

**Comment by DanPurdy** [comment]
Hey @srowhani as mentioned in the previous PR you opened we aren't going to merge this when it makes so many drastic changes across so many rules without tests and documentation for each. You can run the tests locally to make sure it's working and passing before you submit the PR.

I've created this branch, https://github.com/sasstools/sass-lint/tree/feature/auto-fix please open up any PR's into that branch instead of develop and then at least it can serve as a work in progress branch.

And as I say, run the tests locally and lint your code locally before submitting to avoid you having to make lots of little tweak commits like you are above.

Thanks

**Comment by srowhani** [comment]
wow dan not cool, just trying to give back to the people

**Comment by DanPurdy** [comment]
@srowhani I know and we appreciate it but we've given you feedback and clear steps to follow in order to make this as easy as possible for us to review, test and merge in the last PR you opened. It takes a lot of time and effort for us to manage this and we have clear contribution guidelines for people to follow. This isn't meant to discourage you or to prevent you from helping its purely that this takes us a LOT of our spare time to review and test things so we just ask you make it easy for us.

If you read my comment above again you'll see I've opened another branch up for you to contribute in small steps to so that we can start to merge this work in without having to muddy our develop branch. I also mention the fact that you're pushing small commits to fix eslint errors and to run tests when you can do this locally before you push.

I would love to see this work in Sass-lint, just please open the PR up into the new branch I created. 👍

**Comment by jfeldstein** [comment]
Fwiw, this would be an awesome enhancement!

Looking forward to auto-fix and disabling linters via comments before I can switch my team over to it. 

Thanks for the great project

**Pull request closed without merging**
