### PR TITLE
Hotfix Master - no-url-protocols, Fix regex for detecting url protocol use

### LINKED ISSUE #340: no-url-protocols regex too aggressive (reports data-urls)
Here's the offending code (in `/lib/rules/no-url-protocols.js`):

```javascript
var isUrlRegex = /^(http(s?)):\/\/|\/\//;
```

It reports data-urls which have two consecutive slashes in them. The regex should be changed to report urls that begin with `http(s)://` or `//`. There are a number of ways to clean up the regex. Here's my suggested, simplified regex: `/^(https?:)?\/\//`

### PR DESCRIPTION
**Pull request by benthemonkey**
Closes #340 

DCO 1.1 Signed-off-by: Ben Rothman <bensrothman@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
This looks good, just need to update the branch and we can merge it in.

**Comment by benthemonkey** [comment]
rebased.

**Comment by bgriffith** [comment]
We don't generally do it. I think it's easier for everyone to keep track with what's getting merged into develop.

**Comment by bgriffith** [comment]
Update looks good.

**Pull request merged**
