### PR TITLE
Add format and output options to CLI

### LINKED ISSUE #127: Add format option to CLI
Now that we can format the output we should probably provide a `--format` flag to the CLI.

### PR DESCRIPTION
**Pull request by DanPurdy**
Added 2 new flags to the CLI 
* `-f --format [format]`
* `-o --output [output]`

This makes the CLI feature complete compared to the current `sass-lint` build. Format allows you to specify an output format from any of the eslint formatters. Output allows you to specify and output directory & file to write linting results to.

Also added tests for each option.

There's a slight overlap in some of the files added here as in #151 which should probably be merged first due to it fixing bugs.

closes #127 

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Test failing could be to do with the issue in #151, i doubt it very much but will wait to fix this once that has been merged in.

**Comment by DanPurdy** [comment]
Looking at the Travis output, it's installing sass-lint globally at 1.2.0, is the current branch getting merged into that? If not that will be the reasons for the test failing as the new functionality doesn't exist..

**Comment by DanPurdy** [comment]
Now also closes #181

Added another test case and fixed the failing tests

**Comment by bgriffith** [comment]
Looks good.

**Pull request merged**
