### PR TITLE
Hotfix master - Silence output on no errors

### LINKED ISSUE #141: outputResults should only do so if warnings or error present
[outputResults](https://github.com/sasstools/sass-lint/blob/develop/index.js#L96-L106) should only output results if there are warnings or errors present.

### PR DESCRIPTION
**Pull request by DanPurdy**
Silences error output when no warnings or errors are present in linted files. Also improves the handling of writing output to the file system with completion/error messages but no error thrown.

@Snugug - Im hoping this is what you were aiming for, I'll gladly update or revert this if it's not quite what was envisaged.

closes #141 

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Dont merge this yet, wanted to investigate CLI warnings too as this should break them temporarily

**Comment by DanPurdy** [comment]
Closing for now, CLI testing on travis is definitely broken.

**Comment by DanPurdy** [comment]
@bgriffith @Snugug : Ok this confirms to me that the CLI isn't being tested properly, it's being loaded and tested at its latest release. 1.2.0 in this case it looks like. The changes we are making aren't being taken into account as far as the cli is concerned, we'll need to merge our changes into the globally installed sass-lint on Travis too in order to progress with this CLI development.

**Comment by DanPurdy** [comment]
Ok thanks to the addition @mven made, this is now ready for review @bgriffith @Snugug ready for a `1.2.1` release.

**Comment by bgriffith** [comment]
:+1:

**Pull request merged**
