### PR TITLE
Clearer readme for configuring a rule

### PR DESCRIPTION
**Pull request by mrjamesriley**
It took me a few minutes to figure out how to configure a rule, given that there are no complete examples of a `sass-lint.yml` (something that perhaps should be addressed?).

In particular, it wasn't clear to me that the rule configuration needs to be nested under `rules:`, or what the example config shown was doing. I've clarified both of these in this updated readme.

Hope it helps, thanks for the great project. 

DCO 1.1 Signed-off-by: James Riley <webdevjamesriley@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
Thanks, there are actually links in the block above about all of this see [here](https://github.com/sasstools/sass-lint#configuring) including sample configs but I agree this should follow the pattern of the other examples. Can you do me a quick favour though and make sure you include a DCO with your PR.

DCO - https://github.com/sasstools/sass-lint/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin as per our contribution guidelines https://github.com/sasstools/sass-lint/blob/develop/CONTRIBUTING.md#pull-requests

Thanks! 👍

**Comment by mrjamesriley** [comment]
Prompt response there! I've added the DCO, hope that suffices.
(was already added, but with angle brackets either side that had it not showing out of edit view 😷)

**Comment by mrjamesriley** [comment]
(completely overlooked that sample config, thanks for pointing it out)

**Comment by mrjamesriley** [comment]
corrected 😁

**Comment by DanPurdy** [comment]
Thanks 👍

**Pull request merged**
