### PR TITLE
Adds a rule for !important

### LINKED ISSUE #21: New rule: !important
Add a rule that flags up the use of `!important` :fire:

### PR DESCRIPTION
**Pull request by bgriffith**
This adds a basic rule to detect the use of !important. By default it discourages it as this is well known bad practice. Fixes #21.

### CODE REVIEW

**Comment by Snugug** [comment]
* Please rename the rule to `no-important`
* Please use the [add unique](https://github.com/sasstools/sass-lint/blob/master/lib/rules/indentation.js#L43-L49) pattern for adding a detect

**Comment by Snugug** [comment]
And thanks for the contribution!

**Comment by bgriffith** [comment]
No problem, I've updated. If there's anything else, let me know :+1:

**Comment by Snugug** [comment]
Awesome, thanks!

**Pull request merged**
