### PR TITLE
Hotfix develop: Fix ignored files

### LINKED ISSUE #72: Write tests for CLI
The CLI is currently untested (mostly because I don't know how to write tests for it).

This should be figured out, and tests written

### LINKED ISSUE #129: Ignored file still being processed
`sass-lint -v -i tests/sass/border-zero.scss tests/sass/*.scss`

This results in border-zero.scss being processed still.

### PR DESCRIPTION
**Pull request by DanPurdy**
There was an issue with the CLI where ignored files were still being processed as they weren't being passed through to the file globbing.

I took the opportunity to also add basic tests to the ignored files section of the CLI

Waiting on #329 to be merged

Closes #72 
Fixes #129

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by mik01aj** [comment]
Thanks! Could we have a new npm release with it?

**Comment by bgriffith** [comment]
Yep soon aka today :+1:

**Comment by bgriffith** [comment]
@mik01aj 1.3.2 is now on npm

**Comment by mik01aj** [comment]
great, thanks!

**Pull request merged**
