### PR TITLE
Gonzales 3.2 - Fix gonzales-pe version to 3.2.2

### PR DESCRIPTION
**Pull request by danez**
see tonyganch/gonzales-pe#149

Currently I'm not able to install versions > 3.2.2

DCO 1.1 Signed-off-by: Daniel Tschinder <code@tschinder.de>

### CODE REVIEW

**Comment by bgriffith** [comment]
No longer needed as 3.2.6 now installs ok :+1:

**Comment by DanPurdy** [comment]
I think we should definitely fix our versions once we release though. We can setup greenkeeper.io to do the updates for us rather than see different versions with possible regressions break.

**Comment by Snugug** [comment]
I've just enabled Greenkeeper

**Comment by DanPurdy** [comment]
:+1:

**Pull request closed without merging**
