### PR TITLE
Add Appveyor config

### PR DESCRIPTION
**Pull request by Snugug**
Adds Appveyor config so we can test in Windows.

No specific related issue, but we need to have CI for windows

`DCO 1.1 Signed-off-by: Sam Richard <sam@snug.ug>`

I totally messed up #616, let's try it again

### CODE REVIEW

**Comment by Snugug** [comment]
HOW ARE YOU ALREADY OUT OF DATE?!

Either way, this should be GTG now, feel free to merge. All the Node versions are testing as expected

**Comment by DanPurdy** [comment]
😄  Been trying to get all the idle PR's updated or merged so I'd just merged in a new rule that has been added.. I'm confused by these appveyor results, as i mentioned on Slack, both @bgriffith and I are seeing 40+ windows issues when we run it locally on windows but only 2 or 3 in appveyors reporting?

**Comment by DanPurdy** [comment]
Would it be worth specifying an OS?

in linter-sass-lint for example i use 
`os: Windows Server 2012 R2`
can't find any info on appveyor about what their default OS is

**Comment by DanPurdy** [comment]
@Snugug do you wanna update this then, I can't update it to merge it 😭

**Comment by DanPurdy** [comment]
Ignoring Appveyor for now as we can move to fix the issues separately

**Pull request merged**
