### PR TITLE
Hotfix Master - add coveralls

### PR DESCRIPTION
**Pull request by benthemonkey**
Sorry! I broke merging into master because of coveralls.

I cherry-picked the two relevant commits from develop.

DCO 1.1 Signed-off-by: Ben Rothman <bensrothman@gmail.com>

### CODE REVIEW

**Comment by benthemonkey** [comment]
Whyyyyyy

**Comment by benthemonkey** [comment]
@Snugug Do you have coveralls configured to have some coverage threshold? I don't see why the build would fail without a specific coverage requirement being set.

**Comment by DanPurdy** [comment]
Ha it's set to 95% I believe seen as develop was so high in coverage. I think once 1.4.0 is out we should set the limit at 95%, until then it's probably best to just remove this limit for now..

**Comment by benthemonkey** [comment]
So is the setting changed? Should I force push to get it to re-run?

**Comment by Snugug** [comment]
You won't be able to force push. I'll disable it momentarily.

**Comment by Snugug** [comment]
Okay, updated and re-run

**Comment by benthemonkey** [comment]
I've been force-pushing on my forked branches without any issues for some time now. It looks like coveralls isn't reporting back to GitHub now... I'm so sorry about the amount of your time this is taking.

**Comment by benthemonkey** [comment]
Here is the error from Travis: https://travis-ci.org/sasstools/sass-lint/jobs/90841691#L817

**Comment by Snugug** [comment]
Ahh, to yours, not master or develop. 

When I posted it looked like it passed

**Comment by benthemonkey** [comment]
Alright! Looks like we're passing. @DanPurdy or @Snugug want to merge?

**Comment by DanPurdy** [comment]
:+1: I'm still not convinced by this coveralls though, the counts seem a little off and the fact it keeps not reporting a status..

**Pull request merged**
