### PR TITLE
Hotfix lodash dependancy issue by limiting lodash.capitalize version

### LINKED ISSUE #549: Install Issue: lodash - node version
Hi all,
I'm getting the following issue trying to install sass-lint.

```
No compatible version found: lodash.upperfirst@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0

```
I'm running node 4.3.1 and npm 3.75. 

I assume this means that lodash.upperfirst 3.0.0 doesn't support the version of node I'm running, is there anyway round this, other than downgrading my node version (which I don't want to do).

Best,
Max

### PR DESCRIPTION
**Pull request by bgriffith**
Closes #549

DCO 1.1 Signed-off-by: Ben Griffith gt11687@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Good to go. We'll pin it on master until lodash fixes itself

**Comment by jvanaert** [comment]
nice.
are you also releasing a 1.5.1 to npm ?

**Comment by bgriffith** [comment]
@jvanaert Should be on npm now :+1:

**Comment by jvanaert** [comment]
cool ! :+1:

**Pull request merged**
