### PR TITLE
CLI: --fix

### PR DESCRIPTION
**Pull request by srowhani**
**What do the changes you have made achieve?**
- Base implementation of --fix
- Tests
    - Maintain coverage %
    - Test `fix`'s already implemented as demonstration of PR capabilities
        - [ ] `attribute-quotes`
        - [x] `border-zero`
        - [ ] `no-color-keywords`
        - [x] `no-css-comments`
        - [x] `property-sort-order`
        - [ ] `space-before-colon`
        - [ ] `space-after-colon`

**Are there any new warning messages?**

No, `fix` will only run if given `fix` config option.
If fix is run, the only difference is it will rebuild the gonzales ast to be 'correct', and write the new ast into that file.

**Have you written tests?**

Partially, yes. Currently in the process of writing more tests.

**Have you included relevant documentation**

Yes, have added some explanation on how to run `fix`, and how to add your own rule fixes.

**Which issues does this resolve?**
#904
`<DCO 1.1 Signed-off-by: SEENA ROWHANI seenarowhani95@gmail.com>`

Let me know of any concerns or questions. I understand this PR can be risky from your perspective, so I'll do my best to address any comments.

Also, side-note, help adding rules / testing them would be really helpful. So if anyone wants to contribute, feel free to PR my fork 🔥

### CODE REVIEW

**Comment by Grawl** [comment]
🙏

**Comment by graingert** [comment]
I published this as sass-lint-fix and it seems to have an issue with:


```scss
.foo {
  /* something here */
  color: #ffffff!important;
}
```

**Comment by srowhani** [comment]
Hm what's the produced output?

**Comment by graingert** [comment]
@srowhani added after example.

**Comment by srowhani** [comment]
I see. I believe this would be intended, as by default the rule no-css-comments is enabled by sass-lint, and the current implementation of that specific rules `fix` is just to removing them.

**Comment by graingert** [comment]
Ah of course. Thanks!

**Comment by srowhani** [comment]
@DanPurdy I'm having issues squashing this PR. The commit tree has gotten pretty ugly and wouldn't want it being merged in. I'll rebase my changes into a new branch and reopen it.

**Comment by alanalvarado** [comment]
Will this be ready one day ? it has been a year, how can I contribute ?

**Pull request closed without merging**
