### PR TITLE
Add Appveyor config

### PR DESCRIPTION
**Pull request by Snugug**
Adds Appveyor config so we can test in Windows.

No specific related issue, but we need to have CI for windows

`DCO 1.1 Signed-off-by: Sam Richard <sam@snug.ug>`

### CODE REVIEW

**Comment by DanPurdy** [comment]
THANK THE LORDS!!! 😄 

Definitely, lets not make it require for now though until we've got to the gonzales underlying issues! 

:+1:

**Comment by Snugug** [comment]
Don't merge until we hear back from Appveyor

**Comment by Snugug** [comment]
I've also created a Windows Issues epic https://github.com/sasstools/sass-lint/issues/617 for us to throw all of the Windows related issue in to (ZenHub required)

**Comment by Snugug** [comment]
Ugh, gonna need to close this and re-open cause I messed this up

**Pull request closed without merging**
