### PR TITLE
:memo: Fix #241 by updating url

### LINKED ISSUE #241: Broken link in README.md
The link [here](https://github.com/sasstools/sass-lint/blame/develop/README.md#L44) is broken.

### PR DESCRIPTION
**Pull request by Andersos**

### CODE REVIEW

**Comment by Snugug** [comment]
You are missing a description pointing back to the issue you're referencing and the Developer Certificate of Origin. Please refer to our [Contributing Guidelines](https://github.com/sasstools/sass-lint/blob/develop/CONTRIBUTING.md#pull-requests) to ensure your PR is in line with what we request.

**Comment by Andersos** [comment]
Hmm, where do you want me to put the signoff. It says in the comment section of each contribution.
Would that be in the commit or in the pull request comment section? 
DCO 1.1 Signed-off-by: Anders Olsen Sandvik <github@andersos.net>

**Comment by Snugug** [comment]
Pull Request description please

**Comment by Andersos** [comment]
See https://github.com/sasstools/sass-lint/pull/243

**Pull request closed without merging**
