### PR TITLE
Update Gonzales-pe parser to v4.1.1

### PR DESCRIPTION
**Pull request by bgriffith**
~~This PR is a placeholder for updating to Gonzales v4 as there are still a few new bugs introduced on the parser side.~~

### Update

This PR is finally good to go. Many bugs have been fixed within the gonzales-pe parser and all sass-lint tests are now working.

Changes:
- Update package dependancy to `gonzales-pe@v4.1.1`
- Uncomment previously broken tests
- Refactor rules for breaking changes

`<DCO 1.1 Signed-off-by: Ben Griffith gt11687@gmail.com>`

### CODE REVIEW

**Comment by JakeChampion** [comment]
Is there anything I could do to help aid this towards being merged?

**Comment by DanPurdy** [comment]
@JakeChampion There's a few regressions in gonzales v4 iirc (it's been a while...) I think there's also a few rules that need an update. I also need to have another look at the indentation rule as it seems to be broken for Sass now. Will hopefully get a chance to look at it soon.

**Comment by henrahmagix** [comment]
I'd really appreciate this to fix #1084

**Comment by bgriffith** [comment]
@henrahmagix Having another go at this, stay tuned.

**Comment by henrahmagix** [comment]
Thanks!

**Comment by henrahmagix** [comment]
Fantastic, thanks so much @bgriffith!

**Comment by bgriffith** [comment]
@henrahmagix No problem - apologies for it taking so long. Hopefully we can ship a new release asap.

**Pull request merged**
