### PR TITLE
add test cases for sass and include necessary sass test files

### PR DESCRIPTION
**Pull request by saptar**
This PR is an extension to PR https://github.com/sasstools/sass-lint/pull/723 which is already merged.

This PR brings in additional tests to cover .sass syntax.

Tries to Resolve issue https://github.com/sasstools/sass-lint/issues/70

DCO 1.1 Signed-off-by: Saptarshi Dutta <saptarshidutta31@yahoo.co.in>

### CODE REVIEW

**Comment by DanPurdy** [comment]
Thanks @saptar one of the tests here is failing. We'll have to investigate it.

**Comment by ackl** [comment]
FWIW the test that fails on appveyor is fine when run locally on my machine, tested with node v4 v5 & v6

**Comment by DanPurdy** [comment]
@ackl are you on windows using CRLF line endings?

**Comment by ackl** [comment]
@DanPurdy
No I'm not using windows/CRLF line endings. That is indeed the cause of the test failure

I converted to CRLF in the relevant sass file
```$ unix2dos tests/sass/ruleToggler-disable-a-block.sass```
and the test fails.

**Comment by DanPurdy** [comment]
Yep, as assumed 😭 

I'll take a look at gonzales again, thought i'd fixed all the CRLF issues..

**Comment by ackl** [comment]
Did some more digging around, I have a feeling this stems from the way gonzales handles the end of BlockType Nodes.

The ruleToggler tests use the `ruleToggler.getToggledRules`(lib/ruleToggler.js L:64)  method which in turn calls `traverseByTypes` on the gonzales ast.

```
  ast.traverseByTypes(['multilineComment', 'singlelineComment'], function (comment, i, parent) {...}
```
(lib/ruleToggler.js L:74)

Note the `parent` arg in the callback - in the failing test, this is the BlockType Node which is used by the `addDisabledBlock` function to retrieve start/end line/columns.

Thus CRLF after the closing brace on a block in scss files does not adversely affect the `Node.end.column` value which we check for in the tests.

I guess for sass files, with no closing brace to indicate the end of a BlockType Node, gonzales will take the end of line as the end of the block thus including the \r\n chars?

heres some code to illustrate what I mean:
```
let gonzales = require('gonzales-pe');
let scssFilePath = 'path/to/sass-lint/tests/sass/ruleToggler-disable-a-block.scss';
let sassFilePath = 'path/to/sass-lint/tests/sass/ruleToggler-disable-a-block.sass';

let scssAST = gonzales.parse(fs.readFileSync(scssFilePath).toString(), {syntax: 'scss'});
let sassAST = gonzales.parse(fs.readFileSync(sassFilePath).toString(), {syntax: 'sass'});
```

### scssAST 
**with dos line endings**
```
Node {
  type: 'stylesheet',
  ... 
  start: { line: 1, column: 1 },
  end: { line: 3, column: 3 } }
```

**with unix line ending**
```
Node {
  type: 'stylesheet',
  ...
  start: { line: 1, column: 1 },
  end: { line: 3, column: 2 } }
```
#### scssAST traverse to comment Node
```scssAST.traverseByTypes(['multilineComment', 'singlelineComment'], function(comment, i, parent) {console.log(parent)})``` logs **with both unix or dos line endings**

```
Node {
  type: 'block',
  ...
  start: { line: 1, column: 3 },
  end: { line: 3, column: 1 } }
```

### sassAST
**with dos line endings**
```
Node {
  type: 'stylesheet',
  ...
  start: { line: 1, column: 1 },
  end: { line: 2, column: 34 } }
```
**with unix line endings**
```
Node {
  type: 'stylesheet',
  ...
  start: { line: 1, column: 1 },
  end: { line: 2, column: 33 } }
```
#### sassAST traverse to comment Node
```sassAST.traverseByTypes(['multilineComment', 'singlelineComment'], function(comment, i, parent) {console.log(parent)})``` logs **with dos line endings**

```
Node {
  type: 'block',
  ...
  start: { line: 2, column: 1 },
  end: { line: 2, column: 33 } }
```

logs **with unix line endings**
```
Node {
  type: 'block',
  ...
  start: { line: 2, column: 1 },
  end: { line: 2, column: 32 } }
```


hope this helps

**Comment by glen-84** [comment]
@DanPurdy Any news here? #677 will be really useful.

**Comment by DanPurdy** [comment]
Hi @glen-84 I just haven't had any time recently i'm afraid. I will get round to this shortly though!

**Comment by DanPurdy** [comment]
Right going to merge this into the disable-linters branch and look into the problem as soon as possible.

**Pull request merged**
