### PR TITLE
Update gonzales-pe

### PR DESCRIPTION
**Pull request by dane-harnett**
Keen to get this updated as it fixes an issue that is blocking me from migrating to sass-lint from scss-lint

### CODE REVIEW

**Comment by bgriffith** [comment]
We're currently working with the author of gonzles-pe to fix the outstanding parse issues we have with the new release.

**Comment by bgriffith** [comment]
Since there are still issues. We can't update yet.

**Comment by DanPurdy** [comment]
Soon enough! We've got a fair bit of work to do to update sass-lint for all the breaking changes made in 3.0.0 of gonzales-pe as you can see from the test results of your PR but we'll be going as quick as we can once as @bgriffith mentioned the outstanding issues are fixed.

**Comment by dane-harnett** [comment]
@DanPurdy Any movement on this? any way I can help?

**Comment by DanPurdy** [comment]
@dane-harnett nope, unfortunately gonzales still hasn't seen any more updates so we are a little stuck at the moment I'm afraid. If you want to contribute to the gonzales repo with fixes that's the only way to help out at the moment really..

**Pull request closed without merging**
