### PR TITLE
Detect any line ending type regardless of OS.

### PR DESCRIPTION
**Pull request by joshuacc**
Mostly opening this PR to see what Travis has to say about it. I'm still getting some failing tests locally that seem unrelated to the newline issue.

But in case this is acceptable...

DCO 1.1 Signed-off-by: Joshua Clanton <joshua.clanton@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
Thanks for this, the test failures don't seem trivial so we should definitely look into having them pass, Could you also add some tests for the new helper functions please, looking for 100% coverage where we can

**Comment by DanPurdy** [comment]
Just to link this to #154

**Comment by joshuacc** [comment]
@DanPurdy Sorry for the delay on this. Had a long vacation weekend. :grin: 

I've pulled the latest from develop and added tests. Everything newline related passes locally (still one failure that is unrelated to these changes). And it looks like Travis approves as well.

**Comment by joshuacc** [comment]
Correction: Looks like that last failing test on my machine is newline-related after all. It's from the indentation rule, and looks a bit harder to fix than the others. Not necessarily a reason to hold this PR back. I could work on that piece separately.

**Comment by DanPurdy** [comment]
@joshuacc no problem, hope you had a good time!

Thanks very much for this it's looking good to me, I think the indentation rule is heading towards a rewrite anyway due to some of the other issues that have been flagged such as #104, but by all means look into it if you'd like!

I'll have another look over this in the morning and get back to you.

Thanks again

**Comment by DanPurdy** [comment]
@joshuacc this also needs develop merging into it again, we merged a few other PR's this morning.. Sorry! :smile:

**Comment by joshuacc** [comment]
Merged develop into my branch. Travis looks good.

**Comment by DanPurdy** [comment]
Just run through this and tried it out, all working nicely. Thanks @joshuacc

**Comment by joshuacc** [comment]
Awesome. :+1:

**Pull request merged**
