### PR TITLE
Enhance Property Sort Order with presets

### LINKED ISSUE #20: Enhance property-sort-order (other preset orders apart from alphabetical)
One for a rainy day.. It would be great if we could have a few preset orders to chose from (biased for Recess) when configuring the property-sort-order, similar to scss-lint (https://github.com/brigade/scss-lint/tree/master/data/property-sort-orders) and the config (https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder)

### PR DESCRIPTION
**Pull request by bgriffith**
This PR enhances `property sort order` rule with the addition of presets - RECESS, SMACSS and Concentric. It also adds a few helper functions to allow easy loading of config files, retrieval of file extensions and filenames.

Tests for presets have also been included.

Closes #20 

DCO 1.1 Signed-off-by: Ben Griffith <gt11687@gmail.com>

### CODE REVIEW

**Comment by DanPurdy** [comment]
This is good stuff!

Seen as you have the capability to load config files already I think a great addition would be to accept custom order `.yml` files rather than just passing an array of properties in `sass-lint.yml`. What do you think about that?

Once this PR is merged in I'll move ahead and update the colour literal loading into these new helper functions..

**Comment by Snugug** [comment]
Some comments before it gets merged in.

**Comment by bgriffith** [comment]
Updated to use path functions and moved the config files to the config dir.

**Comment by Snugug** [comment]
In the future, instead of one commit to add the files and one commit to delete, them, just include a single rename commit.

A couple more comments, but otherwise looks good!

**Comment by Snugug** [comment]
Please also add test for the new helper function to our list of `helper` tests

**Comment by bgriffith** [comment]
Will do.

**Comment by Snugug** [comment]
Thanks!

**Comment by Snugug** [comment]
I'm confused by the last commits; they seem to be reverting to manual filename and extension parsing instead of using `path`

**Comment by bgriffith** [comment]
Just updated - sorry for the confusion.

**Comment by Snugug** [comment]
Great, thanks.

**Pull request merged**
