### PR TITLE
Feature/write output to file

### LINKED ISSUE #48: Write results to file
One of the features of SCSS Lint that I found useful was the ability to have the results written to a file, with the ability to specify the file path. This would be a really useful addition.

I think it would be useful to silence the console output if writing to a file is chosen.

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #48

`DCO 1.1 Signed-off-by: Sam Richard <snugug@gmail.com>`

### CODE REVIEW

**Comment by DanPurdy** [comment]
Is there any plans to add defining an output directory?

**Comment by Snugug** [comment]
I had only considered outputting results to a file, not a way of outputting multiple files to a directory

**Comment by DanPurdy** [comment]
Makes sense, this is great though. Eslint formatters will be a massive plus to people. 

Great stuff, @bgriffith you should give this a once over too

**Comment by Snugug** [comment]
Haha, the use of ESLint formatters was mostly because I'm too lazy to write my own (and for the life of me I can't figure out why they haven't been blown out in to their own packages yet)

**Comment by DanPurdy** [comment]
Ha yeah, if they aint broken why fix and all that...

**Comment by bgriffith** [comment]
Looking good.

**Pull request merged**
