### PR TITLE
Correct link to Gonzales-PE node types.

### PR DESCRIPTION
**Pull request by jakubs**
DCO 1.1 Signed-off-by: Jakub Skala skala@papucha.cz

### CODE REVIEW

**Comment by DanPurdy** [comment]
Hi please can you include a developer certificate of origin with your pull requests as per our [contribution guidelines](https://github.com/sasstools/sass-lint/blob/develop/CONTRIBUTING.md#pull-requests)

Thanks

**Comment by DanPurdy** [comment]
Thanks @jakubs if you could just hit the update branch button above then i can merge this in for you :+1:

**Comment by DanPurdy** [comment]
Sorry @jakubs you'll need to do it agian, as we just released and updated 1 for 1.5.0. Leave a quick message here when you've clicked update again and I'll merge it straight in for you.

Thanks

**Comment by jakubs** [comment]
OK :-)

**Comment by DanPurdy** [comment]
Thanks!

**Pull request merged**
