### PR TITLE
Add hex length rule

### LINKED ISSUE #73: New Rule: Hex Length
Hex length rule

as per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexlength)

### PR DESCRIPTION
**Pull request by DanPurdy**
Add a rule to enforce the length of hexadecimal values

Closes #73

DCO 1.1 Signed-off-by: Dan Purdy danjpurdy@gmail.com

### CODE REVIEW

**Comment by DanPurdy** [comment]
Ooops on the warning message I added.. changing now.

**Comment by Snugug** [comment]
How does this work if a hex code can't be shortened? If it cannot be shortened, will it throw an error? If not, that should be included in the docs.

**Comment by DanPurdy** [comment]
That's a very good point, I'll look into that now. it'll just need to check to make sure the first 3 values aren't equal to the last 3, should make it more robust either way.

**Comment by DanPurdy** [comment]
I've added a separate block to the docs as the example would be correct in both instances.

Also checking whether values can be shortened or not when the style option is set to short.

**Comment by Snugug** [comment]
Does the `color` type only return hex values, or does it return named color values as well? If it returns named color values, this will error.

**Comment by DanPurdy** [comment]
I did check, it only returns hex values strangely.. 

I'll add some test cases though so we can make sure this doesn't break with updates to gonzales though.

**Comment by Snugug** [comment]
Perfect, thanks

**Comment by DanPurdy** [comment]
That should cover the eventualities, I do find it strange that they aren't returned currently though.

**Comment by Snugug** [comment]
All looks good. Thanks!

**Pull request merged**
