### PR TITLE
Hotfix Master: Fix hex-length short format

### LINKED ISSUE #341: hex-length is wrong about how short hexes work
The test cases and code suggest that the following hex values are equivalent:
`#a2c == #a2ca2c` <= wrong

That's not how it works... This is how it works:
`#a2c == #aa22cc`

(Here's a source: https://www.w3.org/community/webed/wiki/CSS_shorthand_reference#Color)

### PR DESCRIPTION
**Pull request by benthemonkey**
Closes #341 

DCO 1.1 Signed-off-by: Ben Rothman <bensrothman@gmail.com>

### CODE REVIEW

**Comment by benthemonkey** [comment]
And then after this, I'll merge develop into my branch and you'll merge the Develop-branch PR. yeah?

**Comment by DanPurdy** [comment]
Yep exactly, keeps master clear of new changes but allows us to do patch releases for errors such as this one from me! Glad someone's looking out for my stupidity ;)

**Comment by benthemonkey** [comment]
so does it look ready to merge?

**Comment by DanPurdy** [comment]
Just on my way to work, will look when I get in. Looked fine on first glance though..

**Comment by DanPurdy** [comment]
:+1: 

Nice one I still don't know how i managed to go all the way through with it like this!

**Pull request merged**
